### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by sherjilozair** [DerelictOrg/DerelictSFML2#11]
I just wanted to say that this is a poor choice of a name.

<img width="549" alt="screen shot 2018-05-04 at 12 34 44 pm" src="https://user-images.githubusercontent.com/677316/39639990-90032bc0-4f97-11e8-9b24-48c8f0b33a14.png">

**Comment by mdparker** [comment]
Yes, it was an intentional choice.

**Comment by mdparker** [comment]
And for the record, all of the packages used to be released as part of a single code-base called `Derelict`. I first set that up in 2004: http://www.dsource.org/forums/viewtopic.php?t=105
