### ISSUE TITLE
Support for 2.2

### ISSUE THREAD

**Issue by RyanTaker** [DerelictOrg/DerelictSFML2#6]
With the great work on 2.1, an upgrade to 2.2 would be very much appreciated.

**Comment by aldacron** [comment]
Sure, I'll get on it some time in the next few days. Thanks for bringing this to my attention. I don't follow SFML development regularly.

**Comment by aldacron** [comment]
Actually, I take that back. As of now, it looks like CSFML 2.2 hasn't been released yet.

http://www.sfml-dev.org/download/csfml/

**Comment by LaurentTreguier** [comment]
Well, it seems it's been updated to 2.2 not so long ago ; compiled versions and source code is available in your link.

**Comment by aldacron** [comment]
Thanks for the heads up. I'll try to make time for this within the next couple of weeks. In the meantime, If anyone else wants to diff the CSFML 2.1 and 2.2 headers and make the appropriate changes on the D side, I'll happily merge a PR.

**Comment by miotatsu** [comment]
submitted a PR :)

**Comment by aldacron** [comment]
And I'm late, but it's merged. A new tag will follow as soon as I get support for SharedLibVersion implemented and tested.
