### ISSUE TITLE
cannot open shared object file.

### ISSUE THREAD

**Issue by XKY** [DerelictOrg/DerelictSFML2#9]
when i was using Derelict-SFML at Arch Linux, happened this problem.

Compiler: LDC2
IDE: Eclipse Mars with DDT

derelict.util.exception.SharedLibLoadException@../../.dub/packages/derelict-util-2.0.1/source/derelict/util/exception.d(35): Failed to load one or more shared libraries:
	libcsfml-window.so.2.2 - libcsfml-window.so.2.2: cannot open shared object file: No such file or directory
	libcsfml-window.so.2 - libcsfml-window.so.2: cannot open shared object file: No such file or directory

i already installed sfml and csfml by pacman. and my work space had libcsfml-window.so:

project
├── app(bin)
├── app.d
├── libcsfml-window.so
├── libcsfml-window.so.2.2
├── libcsfml-window.so.2.2.0
... audio, graphics, blaha blaha
├── csfml-window-2.dll
... audio, graphics, blaha blaha

**Comment by aldacron** [comment]
Unlike Windows, Linux does not put the application directory on the default library search path. You'll need to find out what the environment variable LD_LIBRARY_PATH is set to on your system and make sure that csfml is installed somewhere on it, or at least that there are symlinks to the csfml binaries somewhere there.

**Comment by aldacron** [comment]
FYI, I've expanded the set of library names the loader looks for. Before, it was not looking for the versionless forms (i.e. libcsfml-window.so, libcsfml-audio.so, and so on). Now it does. That will possibly fix any trouble you may have had loading from the system path, but point about keeping the shared libraries in the executable's directory on Linux still holds -- it's not on the search path.

**Comment by XKY** [comment]
well.. i didn't touch my workspace. i just upgrade to "~>2.0.4" and now, work so fine. thanks!
